title = "FocusCloud"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

#  [[menu.header]]
#    weight = 2
#    name = "Work"
#    url = "/work"
#  [[menu.header]]
#    weight = 3
#    name = "Blog"
#    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Services"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

#  [[menu.footer]]
#    weight = 1
#    name = "A notre sujet"
#    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Nous contacter"
    url = "/contact"
  [[menu.footer]]
    weight = 3
    name = "Blog"
    url = "/blog"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Accueil"

  [params.slider]
    enable = true
    title = "Libérez vos ambitions"
    subtitle = "Nous aimons l'infonuagique publique, c'est notre expertise.<br/>Nous offrons à nos clients les moyens de faire évoluer leurs TI grâce aux meilleures solutions disponibles."

  [params.wrapper]
    enable = true
    title = "A notre sujet"
    italic = "Après de nombreuses années d'expérience en sécurité et infrastructure traditionnelles, les 2 fondateurs de FocusCloud ont acquis une certitude : pour permettre à leur clientèle de se transformer vers une économie digitale, le Cloud publique est la seule possibilité."
    paragraph = "Quand il s'agit de faire évoluer son infrastructure TI, plusieurs concepts sont aujourd'hui incontournable pour permettre à votre compagnie de rencontrer ses objectifs d'affaire : élasticité, puissance de calcul à la demande, capacité d'échange de données, réduction des coûts d'immobilisation, disponibilité maximale... Pour concrétiser ces concepts il existe plusieurs solutions. La plus rapide et la plus efficace est sans conteste l'utilisation de fournisseurs d'infonuagique publique. C'est notre expertise, et c'est pour cela que nous avons foncé FocusCloud"

  [params.blog]
    enable = true
    title = "Prenez connaissance du meilleur de ce qu'on fait"
    subtitle = "La meilleure manière de rester en contact"

  [params.feature]
    enable = true
    title = "Nous nous concentrons sur le meilleur"
    content = "La notion d'infonuagique est souvent mal comprise. En ce qui nous concerne, la définition est claire et correspond à celle fournie par la Cloud Security Alliance (CSA). Pour qu'un fournisseur puisse prétendre fournir de l'infonuagique, ses ressources doivent être consommable à la demande en libre-service, doit être accessible depuis n'importe où sur Internet, partageables librement entre utilisateurs, offrir une élasticité rapide, et enfin être facturable selon leur consommation à la demande et non selon des forfaits.<br/> " 
   # [params.feature.button]
   #   caption = "Voir un exemple"
   #   url = "#"

  [params.call]
    enable = true
    title = "Nous travaillons en permanence pour vous offrir la meilleure expérience Cloud"
    paragraph = "Renseignez vous sur notre travail et notre réputation. Venez nous rencontrer et découvrez à quel point notre focus est en permanence axé sur le Cloud publique et tous ses bénéfices que l'on désire vous faire connaitre."

  [params.contact]
    enable = true
    title = "Laissez nous un message"
    subtitle = "N'hésitez pas à nous demander des exemples de réalisations passées"
    [params.contact.form]
      name = "Votre nom"
      email = "Votre courriel"
      subject = "Le sujet"
      message = "Votre message"
      button = "Envoyer message"
    [params.contact.box]
      title = "Passez nous voir"
      address = "830, rue Eymard G1S4A1 Quebec, Canada"
      email = "Email: contact@focuscloud.ca"
      phone = "Phone: +1 581 999 2940"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
